### ISSUE TITLE
CarPlay sometimes fails to load unless the app is already open on the mobile device

### ISSUE THREAD

**Issue by mitchdowney** [podverse/podverse-rn#1973]
> Platform: ios / Version: 4.13.9 build 2317

> I’m on an iPhone 13, and your app frequently gets hung in CarPlay. This is when I first attempt to access the app. Sometimes I get a completely black screen. Other times I get a Loading screen that never resolves. See attached. this happens more often than it works, unfortunately. 

> Usually if I go to the app directly on my phone, it triggers it to proceed and it works normally from there. But trying through the CarPlay interface fails often. 

![original-7BD01777-B93E-4C2F-A463-C8A9AEFD53DD](https://github.com/podverse/podverse-rn/assets/2262919/d728b17e-fc79-4a5f-9fd1-b484b7378539)

**Comment by harrymash2006** [comment]
I am also facing the same issue in my app which is using react-native-carplay. Unless the phone app is open, the app on the CarPlay do not work and shows blank screen.

**Comment by mitchdowney** [comment]
@harrymash2006 unfortunately this error report would indicate we have not 100% solved this problem, but I can direct you to the logic we added which has _seemed_ to work for all the devices we have tested at least. IIRC we implemented two different scenes to load on app launch, one for Phone, and one for CarPlay, and the CarPlay one handles establishing the bridge with React Native in the app when the app is launched from CarPlay instead of the device.

https://github.com/podverse/podverse-rn/blob/f264a33d86e951fdfaa4edbdfb40502c98f147e2/ios/podverse/AppDelegate.m#L69

**Comment by harrymash2006** [comment]
Hi @mitchdowney actually tried this already in another app too using react-native-carplay but it shows blank screen on Carplay unless the phone app is open.

**Comment by mitchdowney** [comment]
@kreonjr could this be related? https://github.com/birkir/react-native-carplay/pull/158#issuecomment-1820952102

**Comment by G-nn-r** [comment]
I can confirm this is still an issue on 4.16.1, build 2609 (tested on iPhone 13 Mini with iOS 18.0).

**Comment by mitchdowney** [comment]
We are archiving all Github issues and PRs that pertain to the previous generation Podverse. The Podverse dev team is currently 100% focused on the next generation app, and will be only working on next gen Github issues going forward.

If you would like to see a work-in-progress demo of the upcoming Podverse website, please visit https://alpha.podverse.fm. Our tentative release date is Spring 2026.

If you're a developer who may be interested in contributing to Podverse Next-Gen, please see our [Local Dev Setup documentation](https://github.com/podverse/podverse-ops/blob/v5-develop/dev/local-dev-setup.md). We can also be reached through [Matrix or Discord](https://podverse.fm/contact).

I'm sorry for the abrupt announcement, but thank you for your bug reports and feature requests.
